name:  build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    
    env:
      sample-var: value
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: |
        mkdir ${{ matrix.configuration }}
        cp install.msi install-${{ matrix.configuration }}.msi

    - name: Publish-for-signing
      uses: actions/upload-artifact@v3
      with: 
        name: unsigned-artifacts
        path: install-${{ matrix.configuration }}.msi

  perform-signing:
    uses: ./.github/workflows/sign.yml
    with:
      sample-param: blub
