name: echo
on: push
env: 
  wflevel: "value"
jobs:
  build:
    env:
      joblevel: "value"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{vars.ECHOTEXT}}"
          echo ${{ toJson(env) }}
        env: 
          steplevel: "value"
      
