name: echo
on: push
env: 
  wflevel: "value"
jobs:
  build:
    env:
      joblevel: "value"
    runs-on: ubuntu-latest
    steps:
      - id: me
        run: |
          echo "${{vars.ECHOTEXT}}"
          echo '${{ toJson(steps.me) }}'
        env: 
          steplevel: "value"
      
