name: echo
on: push
env: 
  wflevel: "value"
jobs:
  build:
    env:
      joblevel: "value"
    runs-on: ubuntu-latest
    steps:
      - id: me
        run: |
          echo ECHOTEXT "${{vars.ECHOTEXT}}"
          echo job.env '${{ toJson(job.container.env) }}'
          echo env '${{ toJson(env) }}'
        env: 
          steplevel: "value"
      
