name: echo
on: workflow_dispatch
env: 
  wf-level: "value"
jobs:
  build:
    env:
      job-level: "value"
    runs-on: linux-latest
    steps:
      - run: |
          echo "${{vars.ECHOTEXT}}"
          echo ${{ toJson(env) }}
        env: 
          step-level: "value"
      
