name: sign

on: 
  workflow_call:
    inputs: 
      sample-param: { type: string }
    secrets: 
      token: { required: true }

jobs: 
  sign:

    runs-on: windows-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

#    - name: Get-for-signing
#      uses: actions/download-artifact@v3
#      with: 
#        name: unsigned-artifacts
#        path: unsigned-artifacts

    - name: Get-via-Api
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/stefan-wenig/avtest/actions/runs/${{github.run_id}}/artifacts
      env:
        TOKEN: ${{ secrets.token }}
        
    - name: Publish-signed    
      uses: actions/upload-artifact@v3
      with:
        name: artifacts-${{inputs.sample-param}}
        path: unsigned-artifacts
