name: sign

on: 
  workflow_call:
    inputs: 
      sample-param: { type: string }

jobs: 
  sign:

    runs-on: windows-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Get-for-signing
      uses: actions/dowload-artifact@v3
      with: 
        name: unsigned-artifacts

    - name: Publishe-signed
      uses: actions/upload-artifact@v3
      with:
        name: artifacts-${{sample-param}}
        path: unsigned-artifacts
